// Define buzzwords.  Shamelessly stolen from Wikipedia: http://en.wikipedia.org/wiki/List_of_buzzwords
exports.buzzwords = {
  "business": {
    "name": "Business, sales and marketing",
    "words": [
      "Analytics",
      "Ballpark figure",
      "Bandwidth",
      "Business-to-Business \u2013 also known as B2B.",
      "Business-to-Consumer \u2013 also known as B2C.",
      "Best of Breed",
      "Best practices",
      "Bizmeth \u2013 portmanteau of \"business method\".",
      "Boil the frog",
      "Boil the ocean",
      "Brand",
      "Brick-and-mortar",
      "Business process outsourcing \u2013 also known as BPO.",
      "Buzzword compliant",
      "Building Capabilities",
      "Client-centric",
      "Cloud Computing",
      "Close the loop",
      "Co-opetition",
      "Come-to-Jesus moment",
      "Content Marketing",
      "Core competency",
      "Customer-centric(also customer-centric mindset)",
      "Deep dive",
      "Downsizing",
      "Crystallization",
      "Drinking the Kool-Aid \u2013trusting in things offered by authority figures",
      "Employer Branding",
      "Eating your own dogfood \u2013use a product yourself which you sell to others.",
      "Enable",
      "Entitlement",
      "Enterprise",
      "Event horizon",
      "Eyeballs",
      "Free value",
      "Fulfilment issues",
      "Generation Y",
      "Granular",
      "Guard rails",
      "Herding cats",
      "Holistic (approach/integration)",
      "Hyperlocal",
      "Integrated Marketing Solution",
      "Knowledge Process Outsourcing \u2013 also known as KPO.",
      "Leverage",
      "Logistics \u2013 Now commonly used for shipping, and shipping companies",
      "Long Tail",
      "Low Hanging Fruit",
      "Make it pop",
      "Mindshare",
      "Mission Critical",
      "Management Visibility",
      "New economy",
      "Next generation",
      "Offshoring \u2013 also known as Offshore outsourcing, or something being offshorable.",
      "Pain point",
      "Part of our DNA",
      "Peel back the onion",
      "Quick-win",
      "Return on Investment \u2013 also known as ROI.",
      "Reverse fulfilment \u2013 Processing returned products.",
      "Rightshoring",
      "Seamless (integration)",
      "Serum",
      "Share options",
      "Shoot (As in, \"Shoot me an e-mail about that\")",
      "Social Currency",
      "Socialize",
      "Solution",
      "SOX \u2013 abbreviation of Sarbanes-Oxley.",
      "Sustainability",
      "Storytelling",
      "Startup",
      "Strategy",
      "Talent Relationship Management",
      "Tee off (begin something, i.e. a meeting or program)",
      "Touchpoint",
      "Value-added",
      "Visibility"
    ]
  },
  "education": {
    "name": "Education",
    "words": [
      "Accountable talk",
      "Higher-order thinking",
      "Invested in",
      "Run like a business",
      "Student engagement"
    ]
  },
  "general": {
    "name": "General conversation",
    "words": [
      "Alignment",
      "At the end of the day",
      "Break through the clutter",
      "Bring to the table",
      "Buzzword",
      "Calibrate expectations",
      "Clear goal",
      "Countless",
      "Disruptive innovation",
      "Diversity",
      "Empowerment",
      "Exit strategy",
      "Functional training",
      "Face time",
      "Generation X",
      "Globalization",
      "Grow \u2013 as in \"grow the business\".",
      "Headlights - to gain visibility into",
      "Holistic Approach",
      "Impact \u2013 instead of effect as a noun",
      "Leverage \u2013 used as verb to mean magnify, multiply, augment, or increase.",
      "Milestone",
      "Moving forward",
      "New Sincerity",
      "On the runway",
      "Organic growth",
      "Outside the box",
      "Paradigm",
      "Paradigm shift",
      "Proactive",
      "Push the envelope",
      "Reach out \u2013 as in \"I'll reach out to sales to get the latest figures\".",
      "Relaying",
      "Robust",
      "Sea change (transformation)",
      "Sisterhood",
      "Spin-up",
      "Strategic Communication (also known as \"Stratcom\")",
      "Streamline",
      "Survival strategy",
      "Sustainability",
      "Synergy",
      "Touch base",
      "Wellness",
      "Win-win"
    ]
  },
  "other": {
    "name": "Other/Uncategorized",
    "words": [
      "Antifragile",
      "Best-in-class"
    ]
  },
  "politics": {
    "name": "Politics and current affairs",
    "words": [
      "Big society",
      "Information society",
      "Political capital",
      "Statist",
      "Socialist",
      "Capitalist",
      "Stakeholder",
      "Terrorist",
      "Truthiness",
      "Warfighter",
      "Plutocracy",
      "Global Citizen"
    ]
  },
  "science": {
    "name": "Science and technology",
    "words": [
      "4G",
      "Aggregator",
      "Agile",
      "Ajax",
      "Algorithm",
      "Benchmarking",
      "Back-end",
      "Beta",
      "Big data - larger data sets than last month",
      "Bleeding edge",
      "Blog \u2013 plus various other words that incorporate \"blog\"",
      "Bring your own Device - use of personal equipment (usually mobile) in a work environment",
      "Bricks-and-clicks",
      "Clickthrough",
      "Cloud",
      "Collaboration",
      "Content management",
      "Content Management System \u2013 also known as CMS.",
      "Convergence",
      "Cross-platform",
      "Crowdsourcing",
      "Datafication",
      "Data mining - any kind of data collection or analysis, even simple statistics such as taking averages on large data sets",
      "Data science",
      "Deep dive",
      "Design pattern",
      "DevOps",
      "Digital divide",
      "Digital Remastering",
      "Digital Rights Management \u2013 also known as DRM.",
      "Digital signage",
      "Disruptive Technologies",
      "Document management",
      "Dot-bomb",
      "E-learning",
      "Engine",
      "Enterprise Content Management \u2013 also known as ECM.",
      "Enterprise Service Bus \u2013 also known as ESB.",
      "Framework",
      "Folksonomy",
      "Fuzzy logic",
      "HTML5",
      "Immersion",
      "Information superhighway / Information highway",
      "Innovation",
      "Mashup",
      "Mobile",
      "Modularity",
      "Nanotechnology",
      "Netiquette",
      "Next Generation (also \"NextGen\")",
      "Pandering",
      "PaaS",
      "Pizzazz",
      "Podcasting",
      "Portal",
      "Real-time",
      "Responsive",
      "Sensorization",
      "SaaS",
      "Scalability",
      "Skeuomorphic",
      "Social bookmarking",
      "Social software",
      "Spam",
      "Struts",
      "Sync-up",
      "Systems Development Life-Cycle",
      "Tagging",
      "Think outside the box",
      "Transmedia",
      "User generated content",
      "Viral",
      "Virtualization",
      "Vlogging",
      "Vortal",
      "Web 2.0",
      "Webinar",
      "Weblog",
      "Web services",
      "Wikiality",
      "Workflow"
    ]
  }
}